var fs = require('fs');
var file = 'src/styles/main.css';
var css = fs.readFileSync(file, 'utf8');

var L = [];
L.push('');
L.push('/* === Premium Micro-Interactions (Pillar B) === */');
L.push('');
L.push('.cell:hover {');
L.push('    transform: scale(1.04);');
L.push('}');
L.push('');
L.push('.panel-card {');
L.push('    transition: transform 0.28s cubic-bezier(0.34, 1.56, 0.64, 1), box-shadow 0.28s ease;');
L.push('}');
L.push('.panel-card:hover {');
L.push('    transform: translateY(-3px);');
L.push('    box-shadow: inset 0 0 0 1px rgba(90, 60, 30, 0.08), 0 20px 32px rgba(83, 49, 17, 0.12);');
L.push('}');
L.push('');
L.push('.board-frame {');
L.push('    transition: box-shadow 0.35s ease, transform 0.35s ease;');
L.push('}');
L.push('.board-frame:hover {');
L.push('    box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.65), 0 28px 48px rgba(94, 52, 18, 0.22), 0 0 40px rgba(209, 123, 48, 0.08);');
L.push('}');
L.push('');
L.push('@keyframes placeRipple {');
L.push('    0% { box-shadow: 0 0 0 0 rgba(255, 193, 82, 0.5); }');
L.push('    70% { box-shadow: 0 0 0 10px rgba(255, 193, 82, 0); }');
L.push('    100% { box-shadow: 0 0 0 0 rgba(255, 193, 82, 0); }');
L.push('}');
L.push('.stone.fresh {');
L.push('    animation: landingPop 0.32s ease, placeRipple 0.6s ease 0.1s;');
L.push('}');
L.push('');
L.push('@keyframes lastMoveBreath {');
L.push('    0% { opacity: 0.75; box-shadow: 0 0 6px rgba(241, 199, 92, 0.3); }');
L.push('    100% { opacity: 1; box-shadow: 0 0 14px rgba(241, 199, 92, 0.6); }');
L.push('}');
L.push('.last-move-marker {');
L.push('    animation: lastMoveBreath 2.2s ease-in-out infinite alternate;');
L.push('}');
L.push('');
L.push('@keyframes btnShineSweep {');
L.push('    0%, 80% { left: -75%; }');
L.push('    100% { left: 150%; }');
L.push('}');
L.push('.option-btn.active {');
L.push('    position: relative;');
L.push('    overflow: hidden;');
L.push('}');
L.push('.option-btn.active::after {');
L.push('    content: "";');
L.push('    position: absolute;');
L.push('    top: -50%;');
L.push('    left: -75%;');
L.push('    width: 50%;');
L.push('    height: 200%;');
L.push('    background: linear-gradient(90deg, transparent, rgba(255,255,255,0.18), transparent);');
L.push('    transform: skewX(-20deg);');
L.push('    animation: btnShineSweep 2.8s ease-in-out infinite;');
L.push('}');
L.push('');
L.push('@keyframes messageSlideIn {');
L.push('    from { opacity: 0; transform: translateY(8px); }');
L.push('    to { opacity: 1; transform: translateY(0); }');
L.push('}');
L.push('.message {');
L.push('    animation: messageSlideIn 0.35s cubic-bezier(0.22, 1, 0.36, 1);');
L.push('}');
L.push('');
L.push('@keyframes titleShimmer {');
L.push('    0%, 100% { background-position: 0% center; }');
L.push('    50% { background-position: 100% center; }');
L.push('}');
L.push('.hero h1 {');
L.push('    background: linear-gradient(135deg, var(--ink) 0%, var(--accent-deep) 50%, var(--ink) 100%);');
L.push('    background-size: 200% auto;');
L.push('    -webkit-background-clip: text;');
L.push('    background-clip: text;');
L.push('    -webkit-text-fill-color: transparent;');
L.push('    animation: titleShimmer 6s ease-in-out infinite;');
L.push('}');
L.push('');

var insertBefore = '/* === OS Dark Mode Preference === */';
var idx = css.indexOf(insertBefore);
if (idx === -1) { console.log('Insert point not found'); process.exit(1); }
css = css.substring(0, idx) + L.join('\n') + '\n' + css.substring(idx);
fs.writeFileSync(file, css, 'utf8');
console.log('Premium micro-interactions added successfully');
